### ISSUE TITLE
This action is broken on self hosted runners

### ISSUE THREAD

**Issue by margeauxg-medium** [bigwheel/get-terraform-version-action#2]
Due to the use of `${{ github.action_path }}`. See https://github.com/actions/runner/issues/716

**Comment by bigwheel** [comment]
@margeauxg-medium 
Sorry I don't use this action by myself in few months.
I guess this will be resolved by https://github.com/actions/runner/issues/716#issuecomment-795238933 , right ?

> seems like env variable GITHUB_ACTION_PATH set to correct path. so step could be called via GITHUB_ACTION_PATH instead of ${{ github.action_path }}
> 
> ```
>   - run: ${GITHUB_ACTION_PATH}/setup.sh
>     shell: sh
> ```

**Comment by margeauxg-medium** [comment]
hi @bigwheel 

No problem, just sharing what I discovered in my testing. I've tested with `${GITHUB_ACTION_PATH}` locally and it does work on my self hosted runners. However I'm not sure of the implications of that on Github hosted runners.

**Comment by bigwheel** [comment]
@margeauxg-medium 
I think this problem will be fixed in https://github.com/bigwheel/get-terraform-version-action/releases/tag/v1.3.0 .
I would apprecate if you agree to fix with your environment test (because I don't have Self Hosted Runner environment).
